### ISSUE TITLE
Peer Review #2 From Diana Shen

### ISSUE THREAD

**Issue by DianaShen1224** [mushroomcarbon/TTCDelays#1]
I am peer-reviewing Andrew's paper on TTC Delay.
Strong positive points

The paper has a very interesting analysis and discussion about the TTC delay, which was easy for readers with no statistics or crime background to understand. The choice of topic is relevant to our lives and the language used is very emotive and makes the reader very willing to read on.

Critical improvements needed
- More information may be provided in the abstract. What was found and why does this matter? As from the current abstract, we don’t know what this paper looks like.
- The link at the end of the first page needs to be updated.
- In-text citation of packages and how and where to get the data needed to be added in the introduction part.
- Need to cite R  in the "main content" (refer to rubric).
- Need to add the structure of the article and findings in the introduction.
- A description or explanation of all the variables that appear in the dataset needs to be added.

Please consider adding/changing/removing:
It might be better to put the figure you are referencing in the data section closer to the paragraph you are talking about, which will make it easier to find what you are talking about while it is happening.
It might be better to add some weaknesses to the discussion part which makes the paper more confidential. 
Score: 49 out of 69
Estimated mark:
1: R is cited (1 pt)
Mark: 1/1
2: LLM Usage is documented (1 pt)
Mark: 1/1
3: Title (2 pts)
Mark: 2/2
4: Author, Date, and Repo (2 pts)
Mark: 1/2
The link at the end of the first page needs to be updated.
5: Abstract (4 pts)
Mark: 2/4
The abstract should provide What was found and why this matters. from the current abstract, we don’t know what this paper looks like.
6: Introduction (4 pts)
Mark: 2/4
In-text citation of packages and how and where to get the data needed to be added in the introduction part.
7: Data (10 pts)
Mark: 8/10
A description or explanation of all the variables that appear in the dataset needs to be added.
8: Measurement (4 pts)
Mark: 3/4
There should be more in-depth discussion at a higher level, and the total discussion should be at least 25% of the paper.
9: Cross-References (2 pts)
Mark: 2/2
10: Prose (6 pts)
Mark: 6/6
11: Graphs/Tables (4 pts)
Mark: 4/4
Figures and tables are meaningful and informative, and the style of the table is good to read.
12: Referencing (4 pts)
Mark: 4/4
All data sources, software, and literature are properly cited.
13: Commits (2 pts)
Mark: 2/2
There are multiple commits with meaningful messages.
14: Sketches (2 pts)
Mark: 2/2
A general thought process that is in line with the analysis is provided by sketches.
15: Simulation (4 pts)
Mark: 0/4
No simulation for this paper was performed.
16: Tests (4 pts)
Mark: 0/4
No test for this paper was performed.
17: Reproducibility (4 pts)
Mark: 1/4
The README includes content that isn't used in the paper. The analysis is repeatable.
Mark: 1/1
18: Code style (1 pts)
The code in the paper is appropriately styled using a styler or lintr.
19: Caption (2 pts)
Mark: 2/2
All figures and tables have detailed and meaningful captions.
20: General Excellence (3 pts)
Mark: 0/3
The total paper is fluent and complete. The structure of the paper should be improved

**Comment by mushroomcarbon** [comment]
Thank you for the review! Paper has been changed to reflect suggestions.
