### ISSUE TITLE
Peer review(from Mingxuan Liu)

### ISSUE THREAD

**Issue by MingxuanLiu506** [mushroomcarbon/TTCDelays#2]
**Opening statement summary:**
I am peer-reviewing Andrew Goh's paper on TTC Delays: When they Happen and How to Be on Time.

**Strong positive points:**
The paper is well structured and explores the impact of TTC subway and bus delays. The topic of the article is very relevant to life. Using detailed data analysis and data visualization, readers can clearly understand the distribution of TTC delays. The advice provided in the article can help readers better plan their travel time.

**Critical improvements needed:**
1. According to the rubric, it should be cited R package in the article section. Please note that it is mentioned in the grading criteria that without citeR, the entire paper will receive a score of 0.
2. Need more details on the processing of the data section, such as how you clean the data and handle outliers.
3. The discussion section is too brief. More detailed data analysis and analysis of the reasons for a certain situation are needed.
4. More background information can be added to the introduction so that the reader can better understand the topic discussed in depth.

**Suggestions for improvement:**
You can increase the rigor of your analysis by detailing your approach to Data cleansing and how to handle outliers in more detail in the Data section. In addition, add the introduction section to explain the background of the data studied in more detail. Most importantly, cite R. Finally, the discussion part is supplemented.

**Evaluation:**
Overall this is a very good article with a clear structure and a good demonstration of TTC delay trends and time differences. But with rubric, there are still many things that need to be changed, otherwise you will get a less than ideal score.

**Estimate score:**
75 out of 100

**Reason:**
Most of the deduction points are due to the lack of cite R, and please improve the data processing part and conduct a further analysis of the influencing factors. In general, the content of the article is very attractive and well organized!

**Comment by mushroomcarbon** [comment]
Thank you for the review! Remembered to cite R - good catch on that, didn't know it'd be an automatic 0 :\
