### ISSUE TITLE
Peer-review by Haowei Fan

### ISSUE THREAD

**Issue by HaoweiFan0912** [mushroomcarbon/TTCDelays#3]
# Opening statement summary

Overall, the project has been executed well so far, with a solid structure and reproducibility. However, the paper could benefit from more detailed elaboration.

# Strong positive points

The overall structure of the project is highly professional. All the code is fully reproducible, including the use of seed functions and proper file path management.

# Critical improvements needed

## 
You need to write more tests to thoroughly evaluate your code, which can help prevent the need to rewrite the entire code due to earlier errors.

## 
When uploading your files, you should use more detailed commit messages to clearly outline all the changes you've made.

## 
It seems that your paper is not yet complete, as much of the writing is quite vague. For instance, your abstract does not explain why your research is important or provide specific findings.

# Suggestions for improvement:

## 
I believe it's essential to thoroughly test your code after completing each logical chunk to ensure its functionality and catch any potential issues early.

## 
I recommend uploading your work to GitHub after completing each section, while clearly noting the changes made. If you wait until you've made many changes before uploading, you might forget what was modified earlier, leading to misleading commit messages for your audience.

## 
Your paper should be more detailed, especially in the introduction and abstract, as these sections are the most frequently read. You should ensure that readers can clearly understand what you did, what you discovered, and the methods you used from these two parts.

# Evaluation:
Overall, you are on track to writing a good paper! 20 out of 64.

## Reason:
Disregarding the fact that the R code was not cited, this is a good project. However, considering that this is an incomplete project, the score can only be given as 20 points. These 20 points are derived from your reproducible code, along with the title, author, date, and abstract of the paper.

**Comment by mushroomcarbon** [comment]
Thank you for the review :) Paper was incomplete indeed, many thanks for pointing out what was missing - paper has been updated to reflect that.
