### ISSUE TITLE
Peer Review #2 by Krishna Kumar

### ISSUE THREAD

**Issue by krishnak30** [mushroomcarbon/TTCDelays#4]
**Opening statement summary**
A paper analysing TTC delays and when they happen, based on real data. It analyses data about TTC Bus and Subway delays, summarises key trends, and conveys interesting points about the findings. The repo is structure well, containing all necessary files and folders as outlined by the rubric. 

**Strong positive points**
Chosen topic is very relevant and interesting. The repo is structured very well. The graphs and plots are very well made, aesthetically pleasing, and easy to understand. 

**Critical improvements needed**
•	Packages not cited
•	Some more discussion about the findings and implications of it would be useful
•	A ‘broader context’ is missing from the paper. If x and y are the hour slots most prone to delays, what does this mean for this and this segment of people? What does it mean for office workers or students, etc. 
•	The R scripts are not updated. They are still based on the marriages in-class assignment (especially the simulating, testing, model, and replications scripts)
•	The sketches are not updated, they are the same ones from Professor’s in class sketches
•	The prompts and answers with ChatGPT are not clear

**Suggestions for improvement:**
•	Remove the word ‘LINK’ from the footnote on the introduction page (i.e. remove ‘LINK’ from the ‘thanks’ section in the top matter of your paper’s code)
•	Remove the word ‘Type’ from the legend in figure 1. It doesn’t seem very relevant since the colours and the Bus and Subway are pretty self-explanatory. Plus since they’re all merged
•	Talk more in the discussion section about the findings and broader context
•	Remove the model and replications scripts as they are not relevant
•	Update sketches
•	Update/improve LLM usage file

**Evaluation:** 
The paper has a good theme, topic, and point of view. Some further analysis and discussion would be helpful for the reader to understand the paper better. The figures are very good: Appropriate, well made, and well captioned. 

**Estimated mark:**
R cited: 1
LLM Usage documents: 0
Title: 1 (doesn't indicate end result)
Author, date, repo: 2
Abstract: 2
Intro: 2 (can include some results so intro can be standalone)
Data: 6
Measurement: 3
Cross references: 2
Prose: 6
Graphs/tables: 4
Referencing: 3
Commits: 2
Sketches: 0
Simulation: 0
Tests: 0
Reproducibility: 3
Code style: 1
General excellence: 1

**Estimated Mark:**
40 out of 64

**Reason:**
The paper is good but needs improvement on the technical aspects, as well as some improvements to the discussion section of the paper.

**Comment by mushroomcarbon** [comment]
Thanks for the review :) Very helpful suggestions, pretty much just ran through them line-by-line and changed the paper that way. Paper updated to reflect suggestions
